### ISSUE TITLE
SimCity 2000

### ISSUE THREAD

**Issue by Emendo12** [SirFluffDev/rarch3ds_forwarder_creator#1]
I keep getting a non-working CIA for SimCity 2000. Could it be an issue with this program? I can't figure it out.

**Comment by SirFluffDev** [comment]
Hello! It most likely is an issue with this program.
I'm not really maintaining this anymore, mostly due to the fact that even I'm not sure how it works.
I'd recommend just using regular RetroArch to run PS1 games.

**Comment by SirFluffDev** [comment]
@Emendo12 I do have an idea that I plan to work on, although I'm not 100 percent sure on it. The main issue for me was that I didn't write the actual program myself, as it was made by Sakitoshi. I didn't really know how any of the code worked. I will try to make a new version of the tool though, because I love to have my stuff on the home menu too. It just might take a while. Sorry to disappoint. If I start to get things going again though, I'll let you know.
